const sidebar = document.querySelector('#sidebar');
const pageTitle = document.querySelector('#pageTitle');
const content = document.querySelector('#dashboard');
const footer = document.querySelector('.footer');
const toast = document.querySelector('#toast');
const dashboardView = content.innerHTML;

const paymentRows = [
  ['2026 - 1', 'MATRICULATION FEE', '08/18/2026', '06-2621527-01', '15,329.00'],
  ['2026 - 1', 'MATRICULATION FEE', '08/03/2026', '06-2608603-01', '15,329.00'],
  ['2026 - 1', 'BACK ACCOUNT', '07/16/2026', '06-2592815-01', '14,648.00'],
  ['2025 - 3', 'MATRICULATION FEE', '06/30/2026', '06-2584723-01', '14,648.00'],
  ['2025 - 3', 'MATRICULATION FEE', '05/22/2026', '06-2567966-01', '14,648.00'],
  ['2025 - 2', 'MATRICULATION FEE', '03/20/2026', '06-2526405-01', '16,040.00'],
  ['2025 - 1', 'MATRICULATION FEE', '11/17/2025', '06-2465119-01', '10,986.00'],
];

const curriculumRows = [
  ['CSS140-1', 'Web Application Development', '3'], ['CSS130-1', 'Data Structures and Algorithms', '3'],
  ['ISS160', 'Information Assurance and Security', '3'], ['CSS123P', 'Object-Oriented Programming', '3'],
  ['ITS142P', 'Database Management Systems', '3'], ['ITS152P', 'Software Engineering', '3'],
  ['ITS165-1', 'Information Technology Research', '3'], ['ITS120P', 'Systems Administration', '3'],
  ['CSS153P', 'Computer Graphics', '3'], ['ITS150P', 'Networking Fundamentals', '3'],
];

const pageData = {
  '#announcements': ['Announcements', '<span class="section-kicker">UNIVERSITY NEWS</span><h1>Announcements</h1><p class="intro">The useful stuff, in one place. Check here before asking around.</p>', '<div class="announcement-list portal-list"><article class="announcement-item"><div class="announcement-icon red"></div><div><div class="item-meta"><span>UNIVERSITY NEWS</span><time>Today</time></div><h3>2026-2027 CSC Election is now ongoing</h3><p>Exercise your voice and participate in this year&apos;s student council election.</p></div></article><article class="announcement-item"><div class="announcement-icon blue"></div><div><div class="item-meta"><span>ACADEMIC SERVICES</span><time>Sep 04, 2026</time></div><h3>Online enrollment tutorial is available</h3><p>Review the guide before completing your enrollment requirements.</p></div></article></div>'],
  '#gsa': ['Print GSA', '<span class="section-kicker">ACADEMICS</span><h1>Print GSA</h1><p class="intro">Generate a print-ready summary of your current enrollment.</p>', '<div class="certificate-card"><div><span class="mini-label">GENERAL STUDENT ASSESSMENT</span><h2>Ibrahim Rajan Azor II Romero</h2><p>2024106318 · BS Information Technology · 1st Semester A.Y. 2026–2027</p></div><div class="assessment-number"><span>STATUS</span><strong>Ready</strong></div></div><button class="primary-button" data-toast="GSA print dialog is ready.">Print GSA <span>↗</span></button>'],
  '#grades': ['My Grades', '<span class="section-kicker">ACADEMIC RECORD</span><h1>My Grades</h1><p class="intro">Your academic performance at a glance.</p>', '<div class="data-grid"><div class="data-card grade-highlight"><span class="mini-label">CURRENT GWA</span><strong>1.42</strong><span class="positive">Dean’s Lister standing</span></div><div class="data-card"><span class="mini-label">UNITS COMPLETED</span><strong>96 / 144</strong><span class="muted">67% of curriculum</span></div></div><div class="table-card"><div class="table-title"><h2>1st Semester A.Y. 2026–2027</h2><span class="status-pill">In progress</span></div><table><thead><tr><th>Course</th><th>Description</th><th>Units</th><th>Grade</th></tr></thead><tbody><tr><td>CSS140-1</td><td>Web Application Development</td><td>3</td><td class="pending">--</td></tr><tr><td>ITS152P</td><td>Software Engineering</td><td>3</td><td class="pending">--</td></tr><tr><td>ISS160</td><td>Information Assurance and Security</td><td>3</td><td class="pending">--</td></tr></tbody></table></div>'],
  '#curriculum': ['My Curriculum', '<span class="section-kicker">ACADEMIC PROGRESS</span><h1>My Curriculum</h1><p class="intro">Track the courses that make up your Information Technology degree.</p>', `<div class="data-grid"><div class="data-card"><span class="mini-label">PROGRAM</span><strong>BS Information Technology</strong><span class="muted">Curriculum year 2023</span></div><div class="data-card"><span class="mini-label">UNITS LEFT</span><strong>48 units</strong><span class="muted">96 units credited</span></div></div><div class="table-card"><div class="table-title"><h2>Core courses</h2><span class="status-pill">10 courses shown</span></div>${courseTable(curriculumRows)}</div>`],
  '#soa': ['Statement of Account', '<span class="section-kicker">FINANCE</span><h1>Statement of Account</h1><p class="intro">Review your current charges and choose a payment method.</p>', '<div class="balance-banner"><div><span class="mini-label">TOTAL AMOUNT PAYABLE</span><strong>₱ 15,329.00</strong><span>Due September 15, 2026 · 1st Semester A.Y. 2026–2027</span></div><button class="primary-button" data-toast="Payment selection is ready.">Pay now <span>→</span></button></div><div class="table-card"><div class="table-title"><h2>Current charges</h2><span class="status-pill warm">2026 - 1</span></div><table><thead><tr><th>Description</th><th>Date charged</th><th>Reference</th><th class="amount">Amount</th></tr></thead><tbody><tr><td>Fourth payment</td><td>08/03/2026</td><td>5160855</td><td class="amount">₱ 15,329.00</td></tr></tbody></table></div><div class="payment-options"><h2>Payment methods</h2><div class="option-row"><span>Online payment</span><strong>RCBC · LandBank · Maya</strong></div><div class="option-row"><span>Pay in person</span><strong>RCBC Bank · Cebuana · GCash</strong></div><div class="option-row"><span>Financial aid</span><strong>Bukas Installment Plan</strong></div></div>'],
  '#payments': ['Payment History', '<span class="section-kicker">FINANCE</span><h1>Payment History</h1><p class="intro">A record of your payments made through myMapúa.</p>', `<div class="data-grid"><div class="data-card"><span class="mini-label">TOTAL PAID</span><strong>₱ 468,886.00</strong><span class="muted">Since your first term</span></div><div class="data-card"><span class="mini-label">TRANSACTIONS</span><strong>24</strong><span class="muted">Most recent first</span></div></div><div class="table-card"><div class="table-title"><h2>Transaction history</h2><button class="quiet-button" data-toast="Your payment history is ready to print.">Print</button></div>${historyTable()}</div>`],
  '#ecm': ['E-CM', '<span class="section-kicker">STUDENT SERVICES</span><h1>Certificate of Matriculation</h1><p class="intro">Your current assessment and enrollment details.</p>', '<div class="certificate-card"><div><span class="mini-label">MAPÚA UNIVERSITY</span><h2>Certificate of Matriculation and Assessment</h2><p>1st Quarter SY2026–2027</p></div><div class="assessment-number"><span>ASSESSMENT #</span><strong>322D00156691</strong></div></div><div class="data-grid"><div class="data-card"><span class="mini-label">STUDENT NUMBER</span><strong>2024106318</strong><span class="muted">BS Information Technology</span></div><div class="data-card"><span class="mini-label">STUDENT NAME</span><strong>Ibrahim Rajan Azor II Romero</strong><span class="muted">Filipino · Male</span></div></div><button class="primary-button" data-toast="Print dialog is ready.">Print certificate <span>↗</span></button>'],
  '#contact': ['My Contact Info', '<span class="section-kicker">PROFILE</span><h1>My Contact Info</h1><p class="intro">Keep your contact details current so the university can reach you.</p>', '<form class="form-card" id="contactForm"><h2>Personal contact information</h2><div class="form-grid"><label>Smart mobile number<input placeholder="09XX XXX XXXX" /></label><label>Non-smart mobile number<input placeholder="09XX XXX XXXX" /></label><label>Email address<input type="email" value="2024106318@mapua.edu.ph" /></label><label>Emergency contact<input placeholder="Full name and number" /></label></div><button class="primary-button" type="submit">Save changes <span>✓</span></button></form>'],
  '#schedule': ['My Schedule', '<span class="section-kicker">ACADEMICS</span><h1>My Schedule</h1><p class="intro">Your class timetable for the current term.</p>', '<div class="schedule-board"><div class="schedule-board-head"><strong>1st Quarter SY2026–2027</strong><span>Monday to Saturday</span></div><div class="class-row"><strong>10:30 AM – 12:00 PM</strong><span>ITS152P</span><small>MPO604 · Monday</small></div><div class="class-row"><strong>12:00 PM – 01:30 PM</strong><span>ITS142P</span><small>MPO601 · Tuesday</small></div><div class="class-row"><strong>10:30 AM – 12:00 PM</strong><span>CSS140-1</span><small>ONLINE · Wednesday</small></div><div class="class-row"><strong>07:30 AM – 09:00 AM</strong><span>ISS160</span><small>MPO604 · Saturday</small></div></div>'],
  '#documents': ['Academic Documents', '<span class="section-kicker">STUDENT SERVICES</span><h1>Academic Documents</h1><p class="intro">Request official documents from one place.</p>', '<div class="document-grid"><div class="document-card"><span class="quick-icon purple">▤</span><h2>Certificate of enrollment</h2><p>Proof of your current enrollment.</p><button class="quiet-button" data-toast="Request started.">Request document</button></div><div class="document-card"><span class="quick-icon teal">□</span><h2>Transcript of records</h2><p>Official academic record for applications.</p><button class="quiet-button" data-toast="Request started.">Request document</button></div><div class="document-card"><span class="quick-icon orange">▧</span><h2>Certificate of good moral</h2><p>For scholarship and employment needs.</p><button class="quiet-button" data-toast="Request started.">Request document</button></div></div>'],
  '#forms': ['Downloadable Forms / E-CM', '<span class="section-kicker">STUDENT SERVICES</span><h1>Downloadable Forms</h1><p class="intro">Access enrollment forms and your electronic certificate of matriculation.</p>', '<div class="download-list"><div><span class="quick-icon red">⇩</span><section><strong>Electronic Certificate of Matriculation</strong><small>Current term · PDF document</small></section><button class="quiet-button" data-toast="Download prepared.">Download</button></div><div><span class="quick-icon gold">▤</span><section><strong>Course request form</strong><small>Academic services · PDF document</small></section><button class="quiet-button" data-toast="Download prepared.">Download</button></div><div><span class="quick-icon green">▣</span><section><strong>Online enrollment user manual</strong><small>Student guide · PDF document</small></section><button class="quiet-button" data-toast="Download prepared.">Download</button></div></div>'],
  '#counselor': ['Counselor / Feedback', '<span class="section-kicker">SUPPORT &amp; HELP</span><h1>Counselor / Feedback</h1><p class="intro">Reach the right person when you need academic or student support.</p>', '<div class="support-panels"><div class="support-panel"><span class="quick-icon coral">◌</span><h2>Talk to your counselor</h2><p>Ask about your academic plan, wellbeing, or next steps.</p><a class="primary-button" href="mailto:mycounselor@mapua.edu.ph">Email counselor <span>↗</span></a></div><form class="support-panel" id="feedbackForm"><span class="quick-icon gold">✦</span><h2>Send feedback</h2><textarea placeholder="Tell us how we can improve your myMapúa experience"></textarea><button class="primary-button" type="submit">Send feedback <span>→</span></button></form></div>'],
  '#faqs': ['User Manuals & FAQs', '<span class="section-kicker">SUPPORT &amp; HELP</span><h1>User Manuals &amp; FAQs</h1><p class="intro">Quick answers for the tasks you do most often.</p>', '<div class="faq-list"><details open><summary>How do I request an academic document?</summary><p>Choose Academic Documents from Student Services, select a document, and submit your request.</p></details><details><summary>Where can I view my current balance?</summary><p>Open Statement of Account under Finance to see current charges and payment options.</p></details><details><summary>How do I print my GSA?</summary><p>Use Print GSA under Academics. Your current enrollment summary will open in a print-ready view.</p></details></div>'],
  '#settings': ['Settings', '<span class="section-kicker">ACCOUNT</span><h1>Settings</h1><p class="intro">Manage your portal preferences.</p>', '<form class="form-card" id="settingsForm"><h2>Portal preferences</h2><label class="toggle-row"><span><strong>Email notifications</strong><small>Receive reminders about payments and requests.</small></span><input type="checkbox" checked /></label><label class="toggle-row"><span><strong>Compact schedule</strong><small>Show more classes in the schedule view.</small></span><input type="checkbox" /></label><button class="primary-button" type="submit">Save preferences <span>✓</span></button></form>'],
  '#signout': ['Sign out', '<span class="section-kicker">ACCOUNT</span><h1>Sign out</h1><p class="intro">Your portal session is ready to end.</p>', '<div class="signout-card"><div class="support-graphic">↪</div><div><h2>Ready to leave?</h2><p>For your security, sign out when you are finished using myMapúa.</p><button class="primary-button" data-toast="You have been signed out of this demo.">Sign out <span>→</span></button></div></div>'],
  '#terms': ['Terms of Service', '<span class="section-kicker">MAPÚA UNIVERSITY</span><h1>Terms of Service</h1><p class="intro">A short version of the rules for using this student portal.</p>', '<div class="legal-copy"><h2>Use the portal for your own records</h2><p>Keep your account details private and use myMapúa for legitimate academic, finance, and student service tasks.</p><h2>Information can change</h2><p>Balances, schedules, and requests are shown for your account and may change when university records are updated.</p><h2>Need a correction?</h2><p>Contact the helpdesk if something looks wrong. Please include the page name and the time you noticed it.</p></div>'],
  '#privacy': ['Privacy Policy', '<span class="section-kicker">MAPÚA UNIVERSITY</span><h1>Privacy Policy</h1><p class="intro">What the portal keeps track of, in plain language.</p>', '<div class="legal-copy"><h2>Your student records</h2><p>myMapúa displays information connected to your student account, including grades, enrollment, payments, and contact details.</p><h2>Use with care</h2><p>Do not share your student number, account access, or payment information with other people.</p><h2>Questions</h2><p>For privacy concerns, contact the university helpdesk through the contact page.</p></div>'],
};

function courseTable(rows) { return `<table><thead><tr><th>Course code</th><th>Course title</th><th>Credit units</th></tr></thead><tbody>${rows.map((row) => `<tr><td>${row[0]}</td><td>${row[1]}</td><td>${row[2]}</td></tr>`).join('')}</tbody></table>`; }
function historyTable() { return `<table><thead><tr><th>Term</th><th>Description</th><th>Payment date</th><th>OR number</th><th class="amount">Amount</th></tr></thead><tbody>${paymentRows.map((row) => `<tr>${row.slice(0, 4).map((cell) => `<td>${cell}</td>`).join('')}<td class="amount">₱ ${row[4]}</td></tr>`).join('')}</tbody></table>`; }

function showToast(message) { toast.textContent = message; toast.classList.add('show'); window.clearTimeout(showToast.timeout); showToast.timeout = window.setTimeout(() => toast.classList.remove('show'), 2600); }
function bindActions() { document.querySelectorAll('[data-toast]').forEach((button) => button.addEventListener('click', () => showToast(button.dataset.toast))); const helpButton = document.querySelector('#helpButton'); if (helpButton) helpButton.addEventListener('click', () => showToast('Help Center is coming right up.')); document.querySelectorAll('form').forEach((form) => form.addEventListener('submit', (event) => { event.preventDefault(); showToast('Changes saved successfully.'); })); }
function setActiveLink(hash) { document.querySelectorAll('.nav-link').forEach((link) => { const active = link.getAttribute('href') === hash || (hash === '#dashboard' && link.getAttribute('href') === '#dashboard'); link.classList.toggle('active', active); if (active) { const group = link.closest('.nav-group'); if (group) setSectionState(group, true); } }); }
function setSectionState(group, isOpen) { group.classList.toggle('collapsed', !isOpen); const toggle = group.querySelector('.section-toggle'); if (toggle) toggle.setAttribute('aria-expanded', String(isOpen)); }
function initSectionToggles() { document.querySelectorAll('.nav-group').forEach((group, index) => { const toggle = group.querySelector('.section-toggle'); if (!toggle) return; const savedState = window.localStorage.getItem(`mymapua-section-v2-${index}`); setSectionState(group, savedState === 'open'); toggle.addEventListener('click', () => { const isOpen = group.classList.contains('collapsed'); document.querySelectorAll('.nav-group').forEach((otherGroup) => setSectionState(otherGroup, false)); setSectionState(group, isOpen); document.querySelectorAll('.nav-group').forEach((otherGroup, otherIndex) => window.localStorage.setItem(`mymapua-section-v2-${otherIndex}`, otherGroup === group && isOpen ? 'open' : 'closed')); }); }); }
function renderPage() { const hash = window.location.hash || '#dashboard'; const page = pageData[hash]; if (!page) { pageTitle.textContent = 'My Home'; content.innerHTML = dashboardView; footer.hidden = false; setActiveLink('#dashboard'); bindActions(); return; } pageTitle.textContent = page[0]; content.innerHTML = `<section class="page-heading">${page[1]}</section>${page[2]}`; footer.hidden = false; setActiveLink(hash); bindActions(); window.scrollTo({ top: 0, behavior: 'smooth' }); }

document.querySelector('#openMenu').addEventListener('click', () => sidebar.classList.add('open'));
const closeSidebar = () => sidebar.classList.remove('open');
document.querySelector('#closeMenu').addEventListener('click', closeSidebar);
document.querySelector('#sidebarScrim').addEventListener('click', closeSidebar);
document.querySelectorAll('.nav-link').forEach((link) => link.addEventListener('click', closeSidebar));
initSectionToggles();
window.addEventListener('hashchange', renderPage);
renderPage();